local M = {}

M.icons = {
  Class         = "",
  Color         = "",
  Constant      = "ﲀ",
  Constructor   = "",
  Enum          = "",
  EnumMember    = "",
  Event         = "",
  Field         = "",
  File          = "",
  Folder        = "",
  Function      = "",
  Interface     = "ﰮ",
  Keyword       = "",
  Method        = "",
  Module        = "",
  Operator      = "",
  Property      = "",
  Reference     = "",
  Snippet       = "",
  Struct        = "",
  Text          = "",
  TypeParameter = "𝙏",
  Unit          = "",
  Value         = "",
  Variable      = "",

  Table    = "",
  Object   = "",
  Tag      = "",
  Array    = "",
  Boolean  = "",
  Number   = "",
  String   = "",
  Calendar = "",
  Watch    = "",
}

M.codicon = {
  Text          = "",
  Method        = "",
  Function      = '',
  Constructor   = '',
  Field         = '',
  Variable      = '',
  Class         = '',
  Interface     = '',
  Module        = '',
  Property      = '',
  Unit          = '',
  Value         = '',
  Enum          = '',
  Keyword       = '',
  Snippet       = '',
  Color         = '',
  File          = '',
  Reference     = '',
  Folder        = '',
  EnumMember    = '',
  Constant      = '',
  Struct        = '',
  Event         = '',
  Operator      = '',
  TypeParameter = '',

  Table    = "",
  Object   = "",
  Tag      = "",
  Array    = "",
  Boolean  = "",
  Number   = "",
  String   = "",
  Calendar = "",
  Watch    = "",
}

return M
