-- stylua: ignore
return {
	Class         = " ",
	Color         = " ",
	Constant      = "ﲀ ",
	Constructor   = " ",
	Enum          = " ",
	EnumMember    = " ",
	Event         = " ",
	Field         = " ",
	File          = " ",
	Folder        = " ",
	Function      = " ",
	Interface     = "ﰮ ",
	Keyword       = " ",
	Method        = " ",
	Module        = " ",
	Operator      = " ",
	Property      = " ",
	Reference     = " ",
	Snippet       = " ",
	Struct        = " ",
	Text          = " ",
	TypeParameter = "𝙏 ",
	Unit          = " ",
	Value         = " ",
	Variable      = " ",

	Table         = " ",
	Object        = " ",
	Tag           = " ",
	Array         = " ",
	Boolean       = " ",
	Number        = " ",
	String        = " ",
	Calendar      = " ",
	Watch         = " ",
}
